### ISSUE TITLE
Problem on Windows

### ISSUE THREAD

**Issue by pluneau** [pleprince/RfSP#1]
[Script] RenderMan: Writing C:\Users\philippe\Documents\Substance Painter 2\export\RenderMan\RmanExport.json...
[Script] rman: Program 'python.exe rmanAssetsSubstancePainter.py "C:\Users\philippe\Documents\Substance Painter 2\export\RenderMan\RmanExport.json"' failed to start

**Comment by pleprince** [comment]
Hi Philippe
I you go in a shell and type 'python' then return, what's your output ?

**Comment by pluneau** [comment]
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\philippe>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by pleprince** [comment]
and if you run the line manually in the shell ?
`python.exe rmanAssetsSubstancePainter.py "C:\Users\philippe\Documents\Substance Painter 2\export\RenderMan\RmanExport.json"`

**Comment by pluneau** [comment]
C’est bon Philippe, il suffisait juste que je reboote ma station.

Par contre dans Asset Browser quand je génère le rendu du shader avec le petit icone (appareil photo )  tous les shaders sont en magenta ( la sphère est rendu avec un shader magenta).

Par contre dans l’Hypershade le shader semble correct et même quand je l’assigne à un objet le shader est bon

[cid:image003.png@01D24989.AD6BB530]

[cid:image004.png@01D24989.AD6BB530]

[cid:image005.png@01D24989.AD6BB530]



[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : lundi 28 novembre 2016 13:20
À : pleprince/RfSP
Cc : Philippe Luneau; Author
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


and if you run the line manually in the shell ?
python.exe rmanAssetsSubstancePainter.py "C:\Users\philippe\Documents\Substance Painter 2\export\RenderMan\RmanExport.json"

**Comment by pleprince** [comment]
That's a bit strange. Magenta means the map could not be read.
did you check if the maps are actually in the asset directories that were created ?
was there any message in the script editor when you rendered the asset previews ?
can you attach the json files of one of the created assets ? it could be an encoding bug.

**Comment by pluneau** [comment]
Je t’envoie les fichiers rapidement.

Une petite question au passage dans RIS

 je ne trouve plus la pass lpe :shadowcollector


[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : lundi 28 novembre 2016 15:48
À : pleprince/RfSP
Cc : Philippe Luneau; Author
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


That's a bit strange. Magenta means the map could not be read.
did you check if the maps are actually in the asset directories that were created ?
was there any message in the script editor when you rendered the asset previews ?
can you attach the json files of one of the created assets ? it could be an encoding bug.

**Comment by pluneau** [comment]
Voici les erreurs que j’ai dans le script editor :

X00002 {ERROR}   Plugin error: PxrTexture could not open "C:/Program Files/Pixar/RenderManProServer-21.2/lib/RenderManAssetLibrary/Materials/Substance/Body.rmaBody_basecolor.tex" [<Scatter> Object: materialGeoShape Shader: Body_basecolor_tex]
X00002 {ERROR}   Plugin error: PxrTexture could not open "C:/Program Files/Pixar/RenderManProServer-21.2/lib/RenderManAssetLibrary/Materials/Substance/Body.rmaBody_metallic.tex" [<Scatter> Object: materialGeoShape Shader: Body_metallic_tex]
X00002 {ERROR}   Plugin error: PxrTexture could not open "C:/Program Files/Pixar/RenderManProServer-21.2/lib/RenderManAssetLibrary/Materials/Substance/Body.rmaBody_roughness.tex" [<Scatter> Object: materialGeoShape Shader: Body_roughness_tex]
X00002 {ERROR}   Plugin error: PxrBumpMap could not open "C:/Program Files/Pixar/RenderManProServer-21.2/lib/RenderManAssetLibrary/Materials/Substance/Body.rmaBody_height.tex" [<Scatter> Object: materialGeoShape Shader: Body_height_tex]

Et en plus je viens de m’apercevoir qu’il y a des cadenas sue les dossiers qu’il a créé





[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : lundi 28 novembre 2016 15:48
À : pleprince/RfSP
Cc : Philippe Luneau; Author
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


That's a bit strange. Magenta means the map could not be read.
did you check if the maps are actually in the asset directories that were created ?
was there any message in the script editor when you rendered the asset previews ?
can you attach the json files of one of the created assets ? it could be an encoding bug.

**Comment by pleprince** [comment]
This is because you are saving inside the standard library (in the install directory). You should **always** work on a copy of the RenderManAssetsLibrary directory to avoid that sort of problem.

**Comment by pluneau** [comment]
Je venais juste de voir cela et j’ai essayé en dehors de la librairie standard mais j’obtiens toujours une sphère magenta



[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : lundi 28 novembre 2016 16:25
À : pleprince/RfSP
Cc : Philippe Luneau; Author
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


This is because you are saving inside the standard library (in the install directory). You should always work on a copy of the RenderManAssetsLibrary directory to avoid that sort of problem.

**Comment by pluneau** [comment]
Ce que je ne comprends pas c’est qu’il dit qu’il ne trouve pas latexture dans la dossier :

Plugin error: PxrTexture could not open "C:/Program Files/Pixar/RenderManProServer-21.2/lib/RenderManAssetLibrary/Materials/Substance/Body.rmaBody_basecolor.tex" [<Scatter> Object: materialGeoShape Shader: Body_basecolor_tex]

C’est normal car la texture est dans un dossier

C:/Program Files/Pixar/RenderManProServer-21.2/lib/RenderManAssetLibrary/Materials/Substance/Body.rma/Body.rmaBody_basecolor.tex



[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : lundi 28 novembre 2016 16:25
À : pleprince/RfSP
Cc : Philippe Luneau; Author
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


This is because you are saving inside the standard library (in the install directory). You should always work on a copy of the RenderManAssetsLibrary directory to avoid that sort of problem.

**Comment by pleprince** [comment]
yes, but there is a space in "Program Files", so maybe that's all it takes to fail. Spaces and non-ascii characters in paths will (sadly) fail in renderman.

**Comment by pleprince** [comment]
@pluneau, Can you try again on a path without spaces or accents ?

**Comment by bejavi** [comment]
I wonder if it's a permissions issue.  I couldn't create my own section inside the material presets, it gave an error, so I ended up manually creating it.  If it can't write to that directory, perhaps that's the issue.

**Comment by pluneau** [comment]
I still have the same problem

[cid:image001.png@01D24A17.B768AF00]

[cid:image002.png@01D24A17.B768AF00]


[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : lundi 28 novembre 2016 18:28
À : pleprince/RfSP
Cc : Philippe Luneau; Mention
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


@pluneau<https://github.com/pluneau>, Can you try again on a path without spaces or accents ?

**Comment by pleprince** [comment]
@pluneau, can you go to the github "issues" page and directly attach the screenshots here ? I can't see them in your email.

@bejavi, have you tried to work on a copy of the library ? This is the recommended workflow in the documentation. See Library Configuration in https://rmanwiki.pixar.com/display/REN/Preset+Browser+in+Maya.

**Comment by pluneau** [comment]
![capture4](https://cloud.githubusercontent.com/assets/24222605/20708889/5fac11ee-b632-11e6-8e9b-71a1a47d5f89.PNG)
![capture5](https://cloud.githubusercontent.com/assets/24222605/20708888/5fa9883e-b632-11e6-8612-ebe261cae141.PNG)

**Comment by pleprince** [comment]
That makes sense now. The paths are not properly converted to windows format. I can fix that.

**Comment by pleprince** [comment]
@pluneau, can you attach the `asset.json` file in the directory of the "body" asset ?

**Comment by pluneau** [comment]
[asset.json.txt](https://github.com/pleprince/RfSP/files/618917/asset.json.txt)

**Comment by pluneau** [comment]
Hello Philippe,

Can you fix the problem under windows?

**Comment by pleprince** [comment]
I will get a windows setup next week. That will meek things easier.

**Comment by pleprince** [comment]
Hello Philippe
Can you try again with the latest version ?
Thanks

**Comment by pluneau** [comment]
The problem is still there

**Comment by pleprince** [comment]
can you attach the asset.json file in the generated asset directory so I can take a look ?
thanks

**Comment by pluneau** [comment]
[cid:part1.08020502.06090008@free.fr]

Philippe Luneau
Tél.   : 01 49 89 07 88
Gsm : 06 33 53 39 46
20 Allée des Erables . Bat D Paris Nord II
93420 Villepinte - FRANCE
www.progiss.com<http://www.progiss.com/> | info@progiss.com<mailto:info@progiss.com>

[cid:part4.06000304.05090103@free.fr]<http://progiss.com/>




De : Philippe Leprince [mailto:notifications@github.com]
Envoyé : mardi 16 mai 2017 17:51
À : pleprince/RfSP
Cc : Philippe Luneau; Mention
Objet : Re: [pleprince/RfSP] Problem on Windows (#1)


can you attach the asset.json file in the generated asset directory so I can take a look ?
thanks

-

**Comment by pleprince** [comment]
Can you attach directly on the GitHub page please ? otherwise it doesn't work.

**Comment by pluneau** [comment]
[asset.txt](https://github.com/pleprince/RfSP/files/1005145/asset.txt)

**Comment by pluneau** [comment]
rename file .json

**Comment by pluneau** [comment]
Tu as trouvé d'où vient le problème ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>




On Mon, Oct 29, 2018 at 3:54 PM +0100, "Philippe Leprince" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1<https://github.com/pleprince/RfSP/issues/1>.

**Comment by pleprince** [comment]
J’ai fait plein de tests to windows et ca le fait plus…

**Comment by MadSiks** [comment]
Hello, got the same issue can you help me please ?
[Plugin - RenderMan] ERROR: SubprocessError: Program 'python.exe rmanAssetsSubstancePainter.py "D:\RenderManAssetLibrary\Materials\Substance_Painter\RenderMan\RmanExport.json"' failed to start

The export is done but not in the folder I choose in the plugin setup but in the export textures folder.
So the shaders are not created.
