### ISSUE TITLE
Error when exporting after plugin says successful export

### ISSUE THREAD

**Issue by mrtoodles** [pleprince/RfSP#10]
Thu, 27 Sep 2018 23:41:04
C:\Users\matt\Documents\Allegorithmic\Substance Painter\plugins\RenderMan\log.txt
-----------------------
Start !
OK: json read
  err: <type 'exceptions.ImportError'>
     : No module named rfm.rmanAssets
Traceback (most recent call last):
  File "rmanAssetsSubstancePainter.py", line 144, in export
    import rfm.rmanAssets as ra
ImportError: No module named rfm.rmanAssets
ERROR: failed to import rfm.rmanAssets
sys.path : ['C:\\Users\\matt\\Documents\\Allegorithmic\\Substance Painter\\plugins\\RenderMan'
 'C:\\WINDOWS\\SYSTEM32\\python27.zip'
 'C:\\Python27\\DLLs'
 'C:\\Python27\\lib'
 'C:\\Python27\\lib\\plat-win'
 'C:\\Python27\\lib\\lib-tk'
 'C:\\Python27'
 'C:\\Python27\\lib\\site-packages'
 u'C:\\Program Files\\Pixar\\RenderManForMaya-22.1\\scripts']
  err: <type 'exceptions.Exception'>
     : 
Traceback (most recent call last):
  File "rmanAssetsSubstancePainter.py", line 426, in <module>
    export()
  File "rmanAssetsSubstancePainter.py", line 149, in export
    raise Exception
Exception
Exit.

**Comment by pleprince** [comment]
You are trying to use an old version of the plugin with 22.1, which was incompatible. Please download the latest version.
