### ISSUE TITLE
Export Substance Painter Texture Renderman failed

### ISSUE THREAD

**Issue by PaulD95** [pleprince/RfSP#11]
Hello Everyone this is my problem,

When i want to export my texture from substance painter with the Renderman Plugin i get an error "[Plugin - RenderMan] rman: failed to retrieve project url" it's weird because everything is correclty set so if anyone get a issue could be great. I use the last verion of substance painter 2018.2.3 and the 22.2 of Renderman.

Thanks everyone

**Comment by pleprince** [comment]
Can you paste everything that appeared in the Substance painter log ?
Thanks

**Comment by PaulD95** [comment]
"[Scene 3D] 3D scene successfully loaded
[Scene 3D] 3D scene successfully loaded
[Scene 3D] 3D scene successfully loaded
[Scene 3D] 3D scene successfully loaded
[Scene 3D] 3D scene successfully loaded
[Scene 3D] 3D scene successfully loaded
[Scene 3D] 3D scene successfully loaded
[GenericMaterial] Creation of the shader pbr-metal-rough successful
[GenericMaterial] Creation of the shader pbr-metal-rough successful
[GenericMaterial] Creation of the shader preview-material-shader successful
[Plugin - RenderMan] 




[Plugin - RenderMan] rman: failed to retrieve project url"

This is what i get. Thanks a lot for your help

**Comment by Finn752** [comment]
Hey!
I've got the same problem, on Windows and on Mac!
I'm using Maya2018, Renderman 22.1 and Substancepainter 2018.3
I installed python2.7 (by default) and I set the paths for the plugin correctly.
Any ideas?

[Plugin - resources-updater] No project open, resources updater discarded
[Plugin - RenderMan] 




[Plugin - RenderMan] rman: failed to retrieve project url

**Comment by Alex0498** [comment]
Hy ! I have the same problem !

When i want to export my texture from substance painter with the Renderman Plugin i get an error "[Plugin - RenderMan] rman: failed to retrieve project url" it's weird because everything is correclty set I use the last version of substance painter 2018.2.3 and the 22.2 of Renderman.

So if anyone get a issue could be great.
Thank you !

**Comment by pleprince** [comment]
I’ll take a look on Monday. Cheers

**Comment by pleprince** [comment]
Is that still a problem ? Usually, it happens when the project hasn't been saved yet.
I will close this issue next week unless I get a positive answer.
Cheers

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
