### ISSUE TITLE
Purple Texture After Export from substance painter

### ISSUE THREAD

**Issue by PaulD95** [pleprince/RfSP#12]
Hey everyone,

After succeed export my texture from Substance Painter, I have now to apply it on my modelisation. So I import my Library into the RendermanAssetLibrary, my texture is correctly in the folder, but when i want to make a previz or apply on my mesh the texture is purple. So it's weird, previously when i did it when the 21 version it was working perfectly and now no :/ so if you guys get a solution I'm in :D Thanks a lot

**Comment by pleprince** [comment]
Can you attach the asset.json file of the asset ? Thanks

**Comment by PaulD95** [comment]
{
    "RenderManAsset": {
        "usedNodeTypes": [
            "PxrBlend",
            "PxrNormalMap",
            "PxrSurface",
            "PxrTexture",
            "PxrBlend",
            "PxrTexture",
            "PxrTexture",
            "shadingEngine",
            "PxrBlend"
        ],
        "version": 1.1,
        "previewType": "std",
        "asset": {
            "nodeGraph": {
                "dependencies": [
                    "basecolor._MAPID_.tex",
                    "metallic._MAPID_.tex",
                    "normal._MAPID_.tex",
                    "roughness._MAPID_.tex"
                ],
                "nodeList": {
                    "Teapot_diffuseAtten": {
                        "params": {
                            "topRGB": {
                                "type": "color",
                                "value": [
                                    0,
                                    0,
                                    0
                                ]
                            },
                            "operation": {
                                "type": "int",
                                "value": 19
                            },
                            "bottomRGB": {
                                "type": "reference color",
                                "value": null
                            },
                            "topA": {
                                "type": "reference float",
                                "value": null
                            }
                        },
                        "rmanNode": "PxrBlend",
                        "type": "PxrBlend",
                        "nodeClass": "pattern"
                    },
                    "Teapot_normal_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "normal._MAPID_.tex"
                            },
                            "atlasStyle": {
                                "type": "int",
                                "value": 1
                            },
                            "orientation": {
                                "type": "int",
                                "value": 1
                            },
                            "adjustAmount": {
                                "type": "float",
                                "value": 1.0
                            }
                        },
                        "rmanNode": "PxrNormalMap",
                        "type": "PxrNormalMap",
                        "nodeClass": "pattern"
                    },
                    "Teapot_Srf": {
                        "params": {
                            "specularModelType": {
                                "type": "int",
                                "value": 1
                            },
                            "bumpNormal": {
                                "type": "reference normal",
                                "value": null
                            },
                            "specularRoughness": {
                                "type": "reference float",
                                "value": null
                            },
                            "specularFaceColor": {
                                "type": "reference color",
                                "value": null
                            },
                            "specularEdgeColor": {
                                "type": "reference color",
                                "value": null
                            },
                            "diffuseColor": {
                                "type": "reference color",
                                "value": null
                            }
                        },
                        "rmanNode": "PxrSurface",
                        "type": "PxrSurface",
                        "nodeClass": "bxdf"
                    },
                    "Teapot_metallic_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "metallic._MAPID_.tex"
                            },
                            "atlasStyle": {
                                "type": "int",
                                "value": 1
                            },
                            "linearize": {
                                "type": "int",
                                "value": 0
                            }
                        },
                        "rmanNode": "PxrTexture",
                        "type": "PxrTexture",
                        "nodeClass": "pattern"
                    },
                    "Teapot_specFaceColor": {
                        "params": {
                            "operation": {
                                "type": "int",
                                "value": 19
                            },
                            "bottomA": {
                                "type": "float",
                                "value": 1.0
                            },
                            "topA": {
                                "type": "reference float",
                                "value": null
                            },
                            "bottomRGB": {
                                "type": "color",
                                "value": [
                                    0.04,
                                    0.04,
                                    0.04
                                ]
                            },
                            "topRGB": {
                                "type": "reference color",
                                "value": null
                            }
                        },
                        "rmanNode": "PxrBlend",
                        "type": "PxrBlend",
                        "nodeClass": "pattern"
                    },
                    "Teapot_roughness_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "roughness._MAPID_.tex"
                            },
                            "atlasStyle": {
                                "type": "int",
                                "value": 1
                            },
                            "linearize": {
                                "type": "int",
                                "value": 0
                            }
                        },
                        "rmanNode": "PxrTexture",
                        "type": "PxrTexture",
                        "nodeClass": "pattern"
                    },
                    "Teapot_basecolor_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "basecolor._MAPID_.tex"
                            },
                            "atlasStyle": {
                                "type": "int",
                                "value": 1
                            },
                            "linearize": {
                                "type": "int",
                                "value": 1
                            }
                        },
                        "rmanNode": "PxrTexture",
                        "type": "PxrTexture",
                        "nodeClass": "pattern"
                    },
                    "Teapot_Material": {
                        "params": {
                            "surfaceShader": {
                                "type": "reference float[]",
                                "value": null
                            }
                        },
                        "rmanNode": "shadingEngine",
                        "type": "shadingEngine",
                        "nodeClass": "root"
                    },
                    "Teapot_specEdgeColor": {
                        "params": {
                            "operation": {
                                "type": "int",
                                "value": 19
                            },
                            "bottomA": {
                                "type": "float",
                                "value": 1.0
                            },
                            "topA": {
                                "type": "reference float",
                                "value": null
                            },
                            "bottomRGB": {
                                "type": "color",
                                "value": [
                                    1,
                                    1,
                                    1
                                ]
                            },
                            "topRGB": {
                                "type": "reference color",
                                "value": null
                            }
                        },
                        "rmanNode": "PxrBlend",
                        "type": "PxrBlend",
                        "nodeClass": "pattern"
                    }
                },
                "compatibility": {
                    "hostNodeTypes": [],
                    "host": {
                        "version": "2018.2.3",
                        "name": "Substance Painter"
                    },
                    "renderer": {
                        "version": "22.2"
                    }
                },
                "connectionList": [
                    {
                        "src": {
                            "node": "Teapot_Srf",
                            "param": "outColor"
                        },
                        "dst": {
                            "node": "Teapot_Material",
                            "param": "surfaceShader"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_normal_tex",
                            "param": "resultN"
                        },
                        "dst": {
                            "node": "Teapot_Srf",
                            "param": "bumpNormal"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_roughness_tex",
                            "param": "resultR"
                        },
                        "dst": {
                            "node": "Teapot_Srf",
                            "param": "specularRoughness"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_specFaceColor",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Teapot_Srf",
                            "param": "specularFaceColor"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_specEdgeColor",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Teapot_Srf",
                            "param": "specularEdgeColor"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_diffuseAtten",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Teapot_Srf",
                            "param": "diffuseColor"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_basecolor_tex",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Teapot_specEdgeColor",
                            "param": "topRGB"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_basecolor_tex",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Teapot_specFaceColor",
                            "param": "topRGB"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_basecolor_tex",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Teapot_diffuseAtten",
                            "param": "bottomRGB"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_metallic_tex",
                            "param": "resultR"
                        },
                        "dst": {
                            "node": "Teapot_specEdgeColor",
                            "param": "topA"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_metallic_tex",
                            "param": "resultR"
                        },
                        "dst": {
                            "node": "Teapot_specFaceColor",
                            "param": "topA"
                        }
                    },
                    {
                        "src": {
                            "node": "Teapot_metallic_tex",
                            "param": "resultR"
                        },
                        "dst": {
                            "node": "Teapot_diffuseAtten",
                            "param": "topA"
                        }
                    }
                ],
                "metadata": {
                    "author": "pauld",
                    "resolution": "1024 x 1024",
                    "description": "Created by RenderMan for Substance Painter 0.3.0",
                    "version": "1",
                    "created": "2018-10-31 13:44:01"
                }
            }
        },
        "label": "Teapot"
    }
}

This is my file when I try to make my export test

**Comment by pleprince** [comment]
Which Maya version, rfm version, OS version ?

**Comment by pleprince** [comment]
Your textures are exported as `roughness.MAPID.tex` instead of `roughness._MAPID_.tex `.
That's strange.

**Comment by PaulD95** [comment]
my version of maya is 2018.3, i get Windows 10 and Rfm is 22.2 the last one

**Comment by PaulD95** [comment]
Do you think with an update, it can fix the problem ?

**Comment by pleprince** [comment]
I need to test on windows. Next week most likely.

**Comment by Chuudy** [comment]
Hey I had similar problem on windows. My materials in Maya were magenta.
I noticed that absolute paths were parsed to .json file, instead of relative once.
No dependencies were added also.
I fixed the problem. by adding a few lines of code to the python script.
If you're interested in incorporating them to your code, please contact me.

**Comment by PaulD95** [comment]
@Chuudy Yes for sure I'm very interested ;)

**Comment by Chuudy** [comment]
@PaulD95 Please check my fork of the plugin.
https://github.com/Chuudy/RfSP

**Comment by zossowosso** [comment]
Hi Chuudy

fantastic here it did not work anymore
I just tried the one you shared and it's perfect
thank you so much!!!


Windows 10
maya 2018
Renderman 22.3
Python 2.7

beautiful work Philippe
really practical  :-)

**Comment by Chuudy** [comment]
@zossowosso I am glad it works also for you guys :)
