### ISSUE TITLE
failed to retrieve project url

### ISSUE THREAD

**Issue by Finn752** [pleprince/RfSP#14]
Hey!
I've got a problem on Windows and on Mac!
I'm using Maya2018, Renderman 22.1 and Substancepainter 2018.3
I installed python2.7 (by default) and I set the paths for the plugin correctly.
This happens when I set up a new project. When I pick an old project or sample, it says export was successfully. The files are under SubstancePainter/export but there are no files in the folder for the preset Browser. When I open the preset browser in Maya, there is nothing added too.
Any ideas?

Update: Everything was working for the first time with the SubstancePainter sample project called "MeetMat", I tried another sample/ did a new project nothing was working again...

[Plugin - resources-updater] No project open, resources updater discarded
[Plugin - RenderMan]

[Plugin - RenderMan] rman: failed to retrieve project url

Thank you!

**Comment by pleprince** [comment]
Is that still a problem ?
I will close this issue next week unless I get a positive answer.
Cheers

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
