### ISSUE TITLE
[Plugin - RenderMan] failed to retrieve project url ?????

### ISSUE THREAD

**Issue by Alex0498** [pleprince/RfSP#15]
Hello Everyone ! I have a big problem and it is an urgent matter !

When i want to export my texture from substance painter with the Renderman Plugin i get an error "[Plugin - RenderMan] rman: failed to retrieve project url" it's weird because everything is correclty set  I use the last version of substance painter 2018.2.3 and the 22.2 of Renderman.

So if anyone get a issue could be great.
Thank you !

**Comment by JPelphrey** [comment]
Is your SP project saved, or still untitled? I've seen this before but in my case saving the painter project allowed the plugin to export correctly.

**Comment by pleprince** [comment]
Open the texture manager and re-parse the scene if need be.

**Comment by Alex0498** [comment]
It works thank you so much !
