### ISSUE TITLE
Export failed 'RmanExport.json failed to start'

### ISSUE THREAD

**Issue by bart95** [pleprince/RfSP#16]
Hello!

I have followed the instructions the best I can, but I'm hitting a brick wall. On clicking export for either Disney or Pixar materials, Substance Painter claims the export is done but no materials are showing in the preset browser. I check the log and sure enough:

[Plugin - RenderMan] ERROR: SubprocessError: Program 'python.exe rmanAssetsSubstancePainter.py "D:\Work\Maya\Weapon Shop\sourceimages\Textures\RenderMan\RmanExport.json"' failed to start

The textures are all made and exported fine, but nothing is done to take them into Renderman/Maya and form materials with them. I just have a bunch of image files in the sourceimages/textures/renderman folder. I took a look at the preset browser and noticed a few things:

1) The SubstancePainter folder did not appear. I had to make it as a category in the UI itself, then redirect SP to this folder and tried again. Same result.

2) As far as I can tell, maya is pointed at the right RendermanAssetLibrary folder. As in, the duplicate I made that is outside the default location. However the preferences UI differs from what the tutorial documents and video showed, so I am not 100% sure I've done it right. Any help here would be good, but as the newly created categories are showing as folders within the duplicated directory I think that isn't the problem. I fiddled back and forth with different locations and nadda.

3) I noticed the newly made library was 'protected'. I managed to disable it in the library's json file but this didn't fix the issue.

4) I cannot 'create new material' within the preset browser. I can however create new environment maps, it even opens to the exact folder where my textures are kept. But clicking the new material button doesn't do anything.

On the upside I could manually make the materials from here, but I could have achieved this by making a new PxrMat export in Substance Painter. Any help getting the plugin working entirely would be appreciated.

For reference I am using Windows 10 and both Maya and Substance 2018.

**Comment by pleprince** [comment]
Is that still a problem ? The factory material library is protected by default but you can copy it or make a new one (See RenderMan docs).
I will close this issue next week unless I get a positive answer.
Cheers

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
