### ISSUE TITLE
Issue while exporting  'textureSetResolution' not a function

### ISSUE THREAD

**Issue by VickyMess** [pleprince/RfSP#18]
Hello everyone !
I just installed the plugin following the step by step on renderman's website. But each time I try to export for pixar disney or pixar surface I get this error message :

[Script] Scene name: armchair
[Script] UDIM = false
[Script] rman: Property 'textureSetResolution' of object [object Object] is not a function

Any idea what I did to cause that ? and how to fix it ? 

I am using substance painter 2.4.1 (with a PBR MetalRoughHQ), maya 2019, I installed python 2,7 and added it to the PATH Environmental Variable.

**Comment by pleprince** [comment]
Is that still a problem ?
I will close this issue next week unless I get a positive answer.
Cheers

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
