### ISSUE TITLE
Substance to Maya not export

### ISSUE THREAD

**Issue by Sushant304** [pleprince/RfSP#19]
There is no texture in the folder directory while exporting texture from substance. Then i open the folder directory and exported it. It got deleted right after exporting so whats the issue here???
I  am useing python 2.7 and renderman 23.2 and substance 2018.3.3

**Comment by pleprince** [comment]
Is that still a problem ? The exported files get deleted after the RenderMan Asset has been generated and saved.
I will close this issue next week unless I get a positive answer.
Cheers

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
