### ISSUE TITLE
Issue with Release-0.1.3 on Windows

### ISSUE THREAD

**Issue by dayelov** [pleprince/RfSP#2]
Error in lines 420 and 328 of rmanAssetsSubstancePainter.py
KeyError: u'specular'

**Comment by pleprince** [comment]
Thanks for the report.
Which maps did you paint/export in your project ?

**Comment by dayelov** [comment]
PBR Metal-Rough workflow
Channels: base color, height, roughness, metallic, normal

**Comment by dayelov** [comment]
Ok, so it works if I create an empty specular channel in Substance

**Comment by pleprince** [comment]
No worries, I will fix that.

**Comment by pleprince** [comment]
This is fixed.
You can click the green "Clone or Download" button on the main page and choose "Download ZIP" to get the fix. Just replace the old directory with the new one.

**Comment by pleprince** [comment]
Closing this.

**Comment by dayelov** [comment]
Thanks for support and fixing an issue, work like a charm
