### ISSUE TITLE
Renderman Texture Manager adds .png to .tex files needed

### ISSUE THREAD

**Issue by TwoFerns** [pleprince/RfSP#20]
The Renderman to Substance Painter stuff is working good I think but unfortunately naming stuff is getting in the way each time I export.

The pxrSurface the plug in makes is looking for glove.tex but Renderman Texture Manager outputs glove.png.tex when I run it on the Substance painter export directory.

Other than editing each .tex file's name to remove the .png is there a way to fix this naming issue?
![namingissue](https://user-images.githubusercontent.com/62078998/81029761-00736a80-8e3b-11ea-8092-933a1597ed12.jpg)

**Comment by TwoFerns** [comment]
Also noticing it makes and then deletes some textures I need during the export from Substance with the message.
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\user\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\star_bod_normal.png

**Comment by pleprince** [comment]
We adopted the "name.ext.tex" format because it regularly happens that, for example, "glove.png" and "glove.jpg" cohabit in the same scene. People are messy. That's ok. We just don't want to create hard to debug look changes.
Regarding the "file not found" message, I could add an option to skip cleanup (remove original files) if you want to keep them.

**Comment by TwoFerns** [comment]
Oh that makes sense! I guess my difficulty then is the pxrSurface made by substance painter plugin appears to be looking for name.tex instead of name.ext.tex on all textures.

I have four texture sets in substance and it makes the textures and pxrSurface for three of them fine but deletes the textures for the fourth after making its pxrSurface. Ended up exporting the fourths textures separately and rehooking up, not sure why it's getting cleaned. Thanks for any help.

**Comment by pleprince** [comment]
ok. that's a bug. It should look for the correct name. I will check.

**Comment by TwoFerns** [comment]
[Plugin - RenderMan] Scene name: testbake2
[Plugin - RenderMan] UDIM = false
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.69 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn2_basecolor.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn2_roughness.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn2_metallic.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.78 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn2_normal.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.70 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn4_basecolor.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.07 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn4_roughness.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn4_metallic.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.67 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn4_normal.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.69 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn3_basecolor.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn3_roughness.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn3_metallic.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.84 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn3_normal.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.68 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn5_basecolor.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn5_roughness.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn5_metallic.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.67 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn5_normal.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.69 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn1_basecolor.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.07 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn1_roughness.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 0.06 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn1_metallic.png
[Plugin - RenderMan] RenderMan:   |_ Exported in 1.86 sec.: C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\blinn1_normal.png
[Plugin - RenderMan] RenderMan: Writing C:\Users\timjh\Documents\Allegorithmic\Substance Painter\export\RenderMan\RmanExport.json...
[Plugin - RenderMan] RenderMan: Launching rmanAssetsSubstancePainter.py...
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_basecolor.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_metallic.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_normal.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_roughness.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_basecolor.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_metallic.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_normal.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_roughness.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_basecolor.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_metallic.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_normal.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_roughness.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_basecolor.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_metallic.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_normal.png
[Plugin - RenderMan] RenderMan:          cleanup: file not found: C:\\Users\\timjh\\Documents\\Allegorithmic\\Substance Painter\\export\\RenderMan\\blinn1_roughness.png
[Plugin - RenderMan] RenderMan:          
[Plugin - RenderMan] RenderMan: Export successful ! :)

**Comment by TwoFerns** [comment]
Sorry for the dump but this is the log from the substance painter file. The texture manager creates my five materials in maya and is directing to this path (C://Users//timjh//Documents//Allegorithmic//Substance Painter//export//RenderMan/blinn1_basecolor.tex). It also makes then deletes the textures for my first material blinn1. I appreciate that this plugin even exists as I would not know how to hook up pbr materials in Renderman otherwise! Thanks for any help!

**Comment by pleprince** [comment]
can you please attach one of the generated asset folders ?

**Comment by TwoFerns** [comment]
![rendermanfolder](https://user-images.githubusercontent.com/62078998/81719097-76766380-9431-11ea-81b2-c469491005aa.jpg)
Hope this is it, this looks like the folder with the textures it needs. I've plugged some bits to check and it looks like the .tex files that were missing from Substances renderman export folder. I could definitely just plug them all in now but would be great to learn how I messed up installation.

**Comment by pleprince** [comment]
Can you zip it and post it here, please ? Thanks !

**Comment by TwoFerns** [comment]
[testbake2_blinn1.rma.zip](https://github.com/pleprince/RfSP/files/4616980/testbake2_blinn1.rma.zip)

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
