### ISSUE TITLE
Subprocess error: "python.exe rmanAssetsSubstancePainter.py"

### ISSUE THREAD

**Issue by brandopete** [pleprince/RfSP#22]
We are really hoping to be able to use this plugin in our senior film pipeline. I followed the instructions on ​https://renderman.pixar.com/substance-to-renderman best I could. I made sure that I downloaded the most recent version of the plugin from git hub and placed the files correctly within my system. I also made sure that I installed python 2.7.17. When running the plugin, substance painter reported the following warnings and errors (see attatched files) Any help or ideas would be welcome! Thanks!

![SethQuestion](https://user-images.githubusercontent.com/40000216/94227118-b1e06e80-feb6-11ea-93b1-5734bee57360.PNG)

Also, it seems as the though the textures aren't being sent to the renderman asset library that I specified in the configuration of the plugin in, as they are being sent to to the default substance export folder. 

Here's a pic of where I placed the plugin folders: 
![question2](https://user-images.githubusercontent.com/40000216/94227386-99bd1f00-feb7-11ea-9dd4-2231d74e63c0.PNG)

Thanks again!

**Comment by pleprince** [comment]
Hi @brandopete 
On windows, code 9009 means "file not found". Something didn't work but it isn't reported.
Which version of SP are you using ?
Thanks

**Comment by brandopete** [comment]
I am currently using SP 2020.2.1 on Windows

**Comment by pleprince** [comment]
I should update that code to use the new python API.

**Comment by brandopete** [comment]
That would be wonderful!

**Comment by DogeCena** [comment]
Hi !
I'm using SP 2021.1.1, and this issue still exists
Has it been fixed for older versions ?

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
