### ISSUE TITLE
Plugin Updates

### ISSUE THREAD

**Issue by jonsharratt** [pleprince/RfSP#23]
Currently I am a student with CGSpectrum and have been looking into the Pixar Renderman challenges and all things Renderman to learn a bit more and to use it to expand my portfolio.

This lead me to this plugin after watching the fundamentals videos about the Preset Library. As you are no doubt already aware things have moved on a little within the latest version of Substance Painter.

I started writing a new version based heavily on this plugin and just wondered if the plugin is something you are actively working on (I don't want to reinvent the wheel). If not, would you like me to raise a Pull Request on this repository if I can get it done in the coming months ?

Currently have switched to use the Substance Python API, and rather than using `mapexport` I used the new template preset that now has been added for Renderman (PxrSurface) within Substance Painter. I also added a Preset Library browser UI so you can see materials and what not within Substance Painter.

Demo of current progress:
https://vimeo.com/476235608/

Some current Renderman import / dependency issues:

* Had to update `rmanAssets/core.py` to work with Python 3
* Had to update `vstruct.py` to work with Python 3

Are there plans at all to update Renderman `bin` to migrate to Python 3 at all ?

Stay safe !

**Comment by pleprince** [comment]
Hi Jon
I started rewriting everything in python too ! :-)
I tried to watch your video but I got a "Sorry, we couldn’t find that page" message. Are you sure it is not private ?
The python v3 compatibility will come with RenderMan 24.

**Comment by jonsharratt** [comment]
Oh awesome!, I will await the update, and amazing that Renderman 24 will have Python 3 compatibility.

https://vimeo.com/476235608

Should work now 👍

**Comment by pleprince** [comment]
Look I am totally open to cooperation if you have some stuff done already.

**Comment by pleprince** [comment]
What's the point of the preset browser panel ? It didn't seem to do much in your demo, but I am open... :-)

My new UI is quite minimal:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/10943552/98361487-860ee780-2023-11eb-83ce-69c5e1b00d9d.png">

**Comment by pleprince** [comment]
My goal is mostly to use the new APIs and add color management support, which is a 24 feature. After that, Lama support would be a nice extension.

**Comment by jonsharratt** [comment]
I added the material browser to have a play around with scripting just as way for viewing materials so once exported it would show them in there as part of your library and potentially manage multiple library directories rather than setting a single path. Probably a bit overkill to be fair.

Material Browser WIP
https://vimeo.com/476245605

I come from a web / server background my Python skills are certainly a little rusty. I put the current stuff together over last couple of days to try and get a small vertical slice working. Mainly because I would love the workflow in Maya for the Pixar Magic Shop challenge.

Off I go to https://app.livestorm.co/pixar-animation-studios/new-production-shading to learn about Lama 🙈

**Comment by jonsharratt** [comment]
I think it would be worth me waiting for the initial updated version / branch in this repo then can pull down and perhaps contribute from that point.

Certainly would love to help test and put it through its paces / help with any bug fixes 👍

**Comment by pleprince** [comment]
One scenario your preset browser ui would be good for is when you want to overwrite an existing material. interesting !

**Comment by jonsharratt** [comment]
This is heading more to the functionality of the preset library itself but other ideas....

I was thinking perhaps the preset library could be extended to connect to repository (like a package manager). Publish new versions etc.

In the sense you can just have a preset repository continually added within a company and efficiently pull down only the presets you import for the first time to your machine and the specific version.

Even further still it could then act as complete preset model library as you could extend to support to include the location of a model to import as a reference in Maya or declare other dependencies such as custom nodes perhaps.

Watched the Lama talk, looks great! although a fair few concepts went straight over my head.

Wondering if a preview of the node graph from the preset browser might be useful for a Lama preset before you import it once supported.

Might be going to far here and veering off topic, just thought I would share a bit of a brain dump of ideas I was thinking about 🙈

**Comment by pleprince** [comment]
> I was thinking perhaps the preset library could be extended to connect to repository (like a package manager). Publish new versions etc.
I thought about that. But then we need to support a generic VCS API that could interact with arbitrary an VCS/asset manager. That's quite a bit of work because the UI will need to be updated to that query that VCS/asset manager.

> I haven't implemented lama support in the preset browser yet but that's an interesting idea.

**Comment by jonsharratt** [comment]
Awesome stuff, there is plenty of scope to explore things especially with Renderman 24 coming it seems.

Do drop me an update on here if you get a separate development branch pushed up for this plugin and I will endeavour to help test and explore new ideas where appropriate.

Will close the issue for now to keep things tidy, great to chat and excited for the future of presets in Renderman, Substance Painter and Maya.
