### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by owhe121art** [pleprince/RfSP#24]
Hi! I've been trying to install the plugin and I've fixed as much as I could, but I still got something I can't solve; 
and I've run the code into phyton, to get this response :  
```
 >>> python.exe rmanAssetsSubstancePainter.py "D:\cobb\aversianda\RenderMan\RmanExport.json"
  File "<stdin>", line 1
    python.exe rmanAssetsSubstancePainter.py "D:\cobb\aversianda\RenderMan\RmanExport.json" 
                                        ^
SyntaxError: invalid syntax 
```

Thanks!

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
