### ISSUE TITLE
Problem with Adobe Substance 3D Painter v7.2.2.1163

### ISSUE THREAD

**Issue by progiss** [pleprince/RfSP#27]
Hello,
On the latest version the plugin loads well, but each time it starts up it asks for the Renderman Pro Server folder again.

So

**Comment by pleprince** [comment]
Check your OS security/antivirus settings if you are on windows.

**Comment by progiss** [comment]
Hello,

I found a solution. After having copied the 3 files in the C: \ Program Files \ Allegorithmic \ Adobe Substance 3D Painter \ resources \ python \ plugins folder, start Adobe Substance 3D Painter in administrator mode which will create the renderman.prefs file in the C: \ Program Files \ Allegorithmic \ Adobe Substance 3D Painter \ resources \ python \ plugins folder.

Then you can start Adobe Substance 3D Painter normally.

**Comment by pleprince** [comment]
The plug-in folder in which you copy the RfSP files should always be writable by everyone, to allow the plug-in to save its preferences. Otherwise your settings will be forgotten from one session to another.

**Comment by progiss** [comment]
OK

**Comment by nuzzar** [comment]
I don't think it's a good idea to put preferences file in your program folder. To fix this you have to turn off UAC, take ownership of the folder, fix the permission, etc. Tbh, it's an unnecessary complicated process. Ideally, the preferences file should be in the usual folder like Documents.

**Comment by pleprince** [comment]
Thanks, I will move the preferences to a user location.

**Comment by pleprince** [comment]
@progiss @nuzzar The preference file is now saved in the user's home directory.
Please confirm this is working for you. Thanks.

**Comment by nuzzar** [comment]
@pleprince I can confirm that it is working now. I have some question. I got this 'renderman_for_sp.cpython-37.pyc' file in the __pycache__ folder? I'm not sure if it is generated automatically or I copied it when I installed the plugin before. But when I remove this file, it doesn't seem to get generated by the new plugin. Is this file necessary?

**Comment by pleprince** [comment]
@nuzzar Friendly advice: do not touch files you don't know. This file is automatically generated by the python interpreter to speed up execution.
Thanks for confirming it works. Which OS are you using ?

**Comment by nuzzar** [comment]
@pleprince Windows 10. I know it's a cache file. I only remove it temporarily just to check whether it will be generated again or not. I've already put it back to its place.

**Comment by pleprince** [comment]
Thanks @nuzzar ! Closing.
