### ISSUE TITLE
Possible to change resolution from 4k to 8k?

### ISSUE THREAD

**Issue by ssaproductions** [pleprince/RfSP#28]
I was wondering if it was possible to make the plugin use the export settings resolution for the export since I can choose a higer resolution there? Or make it possible to choose the resolution in the export dialog itself?

**Comment by pleprince** [comment]
If it is possible from the python API, I will add it. Thanks.

**Comment by pleprince** [comment]
@ssaproductions Can you download the latest and let me know if that works for you ?
Thanks !

**Comment by ssaproductions** [comment]
> @ssaproductions Can you download the latest and let me know if that works for you ?
> Thanks !

It works perfectly! Thanks for the fast fix Philippe!
