### ISSUE TITLE
Normal map Bake issue

### ISSUE THREAD

**Issue by dayelov** [pleprince/RfSP#3]
Hi,
i have encountered another thing

during export from Substance, one of the maps, which is normal map, saves in world space with no additional details to it. I manually export  tangent space normal map and connect it to a network.

Thanks

**Comment by pleprince** [comment]
Sorry I am not sure I understand. The normal map should already be automatically exported and connected in the shading network.

**Comment by pleprince** [comment]
And normal maps are always in tangent space.
Actually, at the moment if the project exports both a bump and normal map, I only connect the normal map because they are cheaper to render and look better.

**Comment by dayelov** [comment]
yes the thing is its not exported a tangent normal map

**Comment by pleprince** [comment]
Can you send me a project to reproduce your issue ?

**Comment by dayelov** [comment]
yes sure

**Comment by dayelov** [comment]
http://a360.co/2pOkzQL

**Comment by dayelov** [comment]
![image](https://cloud.githubusercontent.com/assets/18569366/26055775/8b196354-3972-11e7-93cf-8ec58b5dc46c.png)

**Comment by dayelov** [comment]
![armadillo](https://cloud.githubusercontent.com/assets/18569366/26055790/a0439f4c-3972-11e7-92b8-73a2c1b37238.jpg)

**Comment by dayelov** [comment]
looks more like a position map has been exported

**Comment by pleprince** [comment]
The exported normal map looks ok to me. How did you generate this image ?

**Comment by dayelov** [comment]
I just put it in a diffuse color to see how it actually looks

**Comment by pleprince** [comment]
here is the normal map I get:
<img width="879" alt="screen shot 2017-05-15 at 13 31 00" src="https://cloud.githubusercontent.com/assets/10943552/26057764/db6cbbbc-3972-11e7-82b0-66197ad2be81.png">

**Comment by dayelov** [comment]
ok, so my normal map is generated correctly, but its not visibile during a rendering

**Comment by pleprince** [comment]
when it is blue like this, it means there is no bump mapping going on. I looked at your normal map and it is pretty much empty.
I added some detail so you can tell the difference:
![screen shot 2017-05-15 at 14 09 16](https://cloud.githubusercontent.com/assets/10943552/26059170/a808db06-3978-11e7-8477-ff3087700005.jpg)
You were painting in the height channel, so I guess I should either:
* combine the height and normal maps in the shading graph.
* export the combined height + normal map in a single texture.
Any preference ?

**Comment by dayelov** [comment]
• export the combined height + normal map in a single texture

this option would be great

**Comment by eugenerockstar** [comment]
Yup .. agreed.  This would be good.  This is what I was meaning in my email Philippe previously.

**Comment by pleprince** [comment]
OK. will do as soon as I have a moment.

**Comment by pleprince** [comment]
This has been done
