### ISSUE TITLE
What do these log comments mean?

### ISSUE THREAD

**Issue by barefoots** [pleprince/RfSP#36]
![Screenshot_1](https://user-images.githubusercontent.com/46009756/137661529-5e755754-21c4-4f9b-9ea4-146c9007d4a8.jpg)

I just wondering what this log means? Anyone able to point me in right direction. 
Thankyou

**Comment by pleprince** [comment]
Your firewall settings are preventing RenderMan from setting up the live statistics connection when rendering the preview.

**Comment by barefoots** [comment]
Thankyou!
