### ISSUE TITLE
plugin hangs substance painter

### ISSUE THREAD

**Issue by burakumincgi** [pleprince/RfSP#37]
Hi, 
I am using win 10 pro, substance painter 7.4.0 and renderman 24.2
The plugins loads fine in substance, I can see the asset browser working, I can add new library folder and so on.
But when I try to export a material, even on a very simple scene, painter will hangs after the export progress bar is complete.
see video link:
https://youtu.be/8l7iU96dAKo

I have tried with a few different projects and waited up to 1h before I force quit the app.
at the moment I have only python 3.7 and 3.9 installed, do I need 2.7 in order for this to work?
also I only have copied this plugin into substance plugin folder (in documents so it is writable) do I need to install the master plugin as well?

thank you.

**Comment by pleprince** [comment]
Thanks for the report and video.
Is there any error in SP's Log window ?
The plugin uses SP's python interpreter, so you don't have to install python yourself.

**Comment by burakumincgi** [comment]
you can see the sp log window in the video on the left, it simply says:
"[StacksExporter] Map export ended", then sp freezes 
is there anything else that I can do or log to give you more info?

**Comment by pleprince** [comment]
To get more feedback, you can change this line:

File: renderman_for_sp.py
103: LOG = Log(loglevel=spl.ERROR)

with:

File: renderman_for_sp.py
103: LOG = Log(loglevel=spl.DBG_INFO)

restart SP and try again.

**Comment by burakumincgi** [comment]
ok, I've enable the log, but I have also tried exporting without color management and it works, only when enabling the ACES-1.2 color management it crashes. the problem when it crashes now is that the log is frozen as well and it is to quick to see what happens and I only end being able to see one single line of the log, which is the same "[StacksExporter] Map export ended" is there a way to save the log to disk automatically?
I know you can export the log from the "help" menu, but I can't access that since even the UI is frozen

**Comment by burakumincgi** [comment]
I think the problem might be my ocio config is not set up as environment variable, I use houdini.env file for ocio, as I do not want ocio applied system wide.
can I hardcode the path to it in the renderman_for_sp.py?
or is the plugin using the ocio files in the ProServer lib?

**Comment by pleprince** [comment]
Let me check if it fails for me too.
Also, do not install the new version: it is crashing on startup for me.

**Comment by burakumincgi** [comment]
the new version of what? sp, ocio, renderman or this plugin?

**Comment by pleprince** [comment]
the new SP with color management

**Comment by burakumincgi** [comment]
which is the one have 7.4, should I revert back to a previous version?

**Comment by pleprince** [comment]
I have found the bug with color spaces. I will commit the fix in a  minute or two.

**Comment by pleprince** [comment]
Please download the latest and try again.

**Comment by pleprince** [comment]
I am testing with 7.2.1. 
7.4 crashes for me: I will try to see if this is my plugin or something else.

**Comment by burakumincgi** [comment]
ok, I will test first the new one with 7.4, if still crashing will install 7.2.1 and retry
thank you for looking into this

**Comment by burakumincgi** [comment]
tested it with a simple scene and with another more complex one, even tested the shader in houdini 19 and renderman, everything works like a charm, plugin is extremely quick.
any info I can give you to see why is crashing on your end with 7.4?
like gpu dirvers version or win os build?

**Comment by pleprince** [comment]
I am on OSX, so it is likely to be something different.

**Comment by pleprince** [comment]
7.3.1 crashes too. Let's try 7.3.0...

**Comment by burakumincgi** [comment]
I see.. hope you find the fix.

thanks again for the new commit.

**Comment by tdanijel** [comment]
Hi @burakumincgi , how did you make it work? I have exact same system, Win10pro, SP latest 7.4 RM 24.2 but I cannot make it work. I tried 7.3 it was the same thing. Note: I had it working before with 3 files copied to the python plugin directory. I tried everything, I need to give up and do something else :) it's driving me crazy :)

This is log it spits out when I open SP:

[Python] failed to load renderman_for_sp plugin

[Python] Traceback (most recent call last):

[Python]   File "C:/Program Files/Allegorithmic/Adobe Substance 3D Painter/resources/python/modules\substance_painter_plugins.py", line 163, in _is_plugin_discarded
    module = importlib.import_module(module_name)

[Python]   File "C:\Program Files\Allegorithmic\Adobe Substance 3D Painter\resources\pythonsdk\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

[Python]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

[Python]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load

[Python]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

[Python]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

[Python]   File "<frozen importlib._bootstrap_external>", line 724, in exec_module

[Python]   File "<frozen importlib._bootstrap_external>", line 860, in get_code

[Python]   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code

[Python]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

[Python]   File "C:/Users/danij/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 7

[Python]     <!DOCTYPE html>

[Python]     ^

[Python] SyntaxError: invalid syntax

**Comment by tdanijel** [comment]
Hi again, sorry for above message, I didn't download updated file properly. It appears to work now, except this line shows up in red:

[StacksExporter] Map export ended
[Python] rman_assets     INFO:  E1127 20:02:49.785000000 154432 server_chttp2.cc:40] {"created":"@1638072169.785000000","description":"No address added out of total 1 resolved","file":"E:\ratnih\ratnih-vc14\grpc\src\core\ext\transport\chttp2\server\chttp2_server.cc","file_line":348,"referenced_errors":[{"created":"@1638072169.785000000","description":"Failed to add port to server","file":"E:\ratnih\ratnih-vc14\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":509,"referenced_errors":[{"created":"@1638072169.785000000","description":"OS Error","file":"E:\ratnih\ratnih-vc14\grpc\src\core\lib\iomgr\tcp_server_windows.cc","file_line":201,"os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}

[Python] rman_assets     INFO:  RZ0000 {WARNING}: RemoteStatsServer - Grpc server failed to start on port -1

Thank you!

**Comment by pleprince** [comment]
RenderMan tried to connect to a socket to pass real-time statistics. The message means that you need to tweak your firewall settings to allow for it. Cheers

**Comment by pleprince** [comment]
Original bug was fixed. closing.
