### ISSUE TITLE
export

### ISSUE THREAD

**Issue by par4g** [pleprince/RfSP#38]
[Python] Traceback (most recent call last):

[Python]   File "C:/Program Files/Pixar/RenderManProServer-24.2\bin\rman_utils\rman_assets\ui.py", line 310, in newMaterial

[Python] if self.hostPrefs.exportMaterial(category, infodict, previewtype):
[Python]   File "C:/Users/pagho/Documents/Adobe/Adobe Substance 3D Painter/python\plugins\renderman_for_sp.py", line 508, in exportMaterial

[Python] ch_colorspace = mappings[ch_type]['ocio']
[Python] KeyError
[Python] : 
[Python] 'Anisotropylevel'

**Comment by pleprince** [comment]
did you update all the files ? Especially `renderman_rules.json` ?

**Comment by pleprince** [comment]
By the way, @par4g, this is a terrible bug report ! 😂
Non-descriptive title, no description, no OS or SP version. You can do better, I am sure... 😉

**Comment by par4g** [comment]
oh, actually I am new here so I didn't know I should provide those details too 😂
currently, I am on Windows 10 21H2 (19044.1387 OS Build) 
the SP version I am using is 7.2.3 build 1197

so I was just testing the plugin and everything works fine with Lama but gets an error when I switch to pxrsurface or Disney the color config I am using is Aces-1.2

**Comment by pleprince** [comment]
ok. looking at the code, it should work for Lama and PxrSurface but not for PxrDisney. Can you check on your end ?

**Comment by par4g** [comment]
yes sure ill try it again i just updated the files

**Comment by par4g** [comment]
![image](https://user-images.githubusercontent.com/66059868/144047528-d0f9e755-61b8-455a-ab5d-c6de26059212.png)
worked fine just had some warnings but its fine

**Comment by pleprince** [comment]
I can add anisotropy level to PxrDisney if that is useful, but you won't be able to control the direction.

**Comment by par4g** [comment]
not so useful frankly speaking it was not exporting for pxrsurface but now it is exporting so the issue got resolved 
you can add it if someone in the future wants to work with PxrDisney 😅 now it is working totally fine for me

And thanks for helping me out 🙏
