### ISSUE TITLE
Pink Icons - Windows.

### ISSUE THREAD

**Issue by eugenerockstar** [pleprince/RfSP#4]
Hey.

For some reason, when I create a Substance material on Windows, it only creates a pink render icon ..

Any ideas PlP ?

**Comment by pleprince** [comment]
Hey Eugene

That was a bug in 21.4. I fixed it for 21.5... which is just around the corner.

**Comment by eugenerockstar** [comment]
Great, thanks.

**Comment by pleprince** [comment]
fixed
