### ISSUE TITLE
Normal map

### ISSUE THREAD

**Issue by zossowosso** [pleprince/RfSP#5]
the normal map are not generated correctly
otherwise everything is fine

**Comment by pleprince** [comment]
Can you explain what's wrong ? It works for me...

**Comment by zossowosso** [comment]
https://s26.postimg.org/yrubpi64p/script.jpg

**Comment by pleprince** [comment]
I would need to check but I believe that if you have a bump channel instead of a normal channel in your SP project, the normal map will be empty. If this is not the case, please send me a SP project to debug.
Thanks :-)

**Comment by zossowosso** [comment]
Hello Philippe
I have prepared a small scene I send you the link
I have the same problem I have to change the normal map
I also sent the substance painter log, as well as the FBX files

https://drive.google.com/uc?id=0Bz2dwZuxtzt6VmJNQi02NUx1b0k&export=download

thank you

PS: file size Exemple_Scene.rar (252M)

**Comment by pleprince** [comment]
fixed
