### ISSUE TITLE
Error at exporting

### ISSUE THREAD

**Issue by hbougard** [pleprince/RfSP#6]
Hello!

I'm getting this when I try to export 
[Plugin - RenderMan] rman: Program 'python.exe rmanAssetsSubstancePainter.py "H:\Users\Harry\Documents\Substance Painter 2\export\RenderMan\RmanExport.json"' failed to start

**Comment by pleprince** [comment]
Do you have python installed ?

**Comment by hbougard** [comment]
Hello!


Sure, Python 2.7 as indicated!


Thanks for reply


________________________________
De: Philippe Leprince <notifications@github.com>
Enviado: martes, 10 de octubre de 2017 3:29 a. m.
Para: pleprince/RfSP
Cc: hbougard; Author
Asunto: Re: [pleprince/RfSP] Error at exporting (#6)


Do you have python installed ?

**Comment by zossowosso** [comment]
Hello
do not install python by default, 
go into the advanced options for created
all libraries and variable environment

**Comment by pleprince** [comment]
Is this still an issue ?

**Comment by pleprince** [comment]
Closing. @hbougard, please re-open if this is still a problem.
