### ISSUE TITLE
Replace maps

### ISSUE THREAD

**Issue by eugenerockstar** [pleprince/RfSP#8]
Hey PLP.

One day, when you're not super busy, can we have an option to decide whether to replace updated maps on export from Painter.

For instance.  If I create a map and export it.  When I go back into substance to make a change to that map, I need to re-name the shader to get it to appear in the browser.  I just want to update the current shader with the new maps.  Otherwise, I end up with multiple shaders and versions.

Hope this makes some sense.

Thanks

Eugene

**Comment by pleprince** [comment]
this is the default behaviour in 24.1. Closing.
